workflows:
  spark-android:
    name: SPARK Android Release
    max_build_duration: 60
    instance_type: mac_mini_m2

    cache:
      cache_paths:
        - ~/.gradle
        - $CM_BUILD_DIR/build

    environment:
      android_signing:
        - spark_keystore
      groups:
        - firebase_credentials
        - play_store
      vars:
        PACKAGE_NAME: "com.spark.dating"
        FLUTTER_VERSION: "stable"
      flutter: stable
      java: 21

    triggering:
      events:
        - push
        - tag
      branch_patterns:
        - pattern: 'main'
          include: true
        - pattern: 'release/*'
          include: true
      tag_patterns:
        - pattern: 'v*'
          include: true

    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$FLUTTER_ROOT" > "$CM_BUILD_DIR/android/local.properties"

      - name: Set up Firebase config
        script: |
          echo $FIREBASE_CONFIG | base64 --decode > $CM_BUILD_DIR/android/app/google-services.json

      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Generate app icons
        script: |
          dart run flutter_launcher_icons
        ignore_failure: true

      - name: Generate native splash
        script: |
          dart run flutter_native_splash:create
        ignore_failure: true

      - name: Analyze code
        script: |
          flutter analyze

      - name: Run tests
        script: |
          flutter test
        ignore_failure: true

      - name: Build APK (Debug)
        script: |
          flutter build apk --debug
        when:
          condition: not tag

      - name: Build APK (Release)
        script: |
          flutter build apk --release
        when:
          condition: tag

      - name: Build App Bundle (Release)
        script: |
          flutter build appbundle --release
        when:
          condition: tag

    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log

    publishing:
      email:
        recipients:
          - dev@sparkdating.app
        notify:
          success: true
          failure: true

      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        submit_as_draft: true
        when:
          condition: tag


  spark-ios:
    name: SPARK iOS Release
    max_build_duration: 90
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: spark_asc

    cache:
      cache_paths:
        - $HOME/Library/Caches/CocoaPods
        - $CM_BUILD_DIR/build

    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.spark.dating
      groups:
        - firebase_credentials
        - app_store
      vars:
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        FLUTTER_VERSION: "stable"
      flutter: stable
      xcode: latest
      cocoapods: default

    triggering:
      events:
        - push
        - tag
      branch_patterns:
        - pattern: 'main'
          include: true
        - pattern: 'release/*'
          include: true

    scripts:
      - name: Set up Firebase config
        script: |
          echo $FIREBASE_IOS_CONFIG | base64 --decode > $CM_BUILD_DIR/ios/Runner/GoogleService-Info.plist

      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Install CocoaPods
        script: |
          cd ios && pod install

      - name: Set up code signing
        script: |
          xcode-project use-profiles

      - name: Build IPA
        script: |
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      email:
        recipients:
          - dev@sparkdating.app
        notify:
          success: true
          failure: true

      app_store_connect:
        auth: integration
        submit_to_testflight: true
        when:
          condition: tag
